global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'php-api'
    static_configs:
      - targets: ['api:80']
    metrics_path: '/api/metrics'
    
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:9104']  # mysqld_exporter
    
  - job_name: 'nginx'
    static_configs:
      - targets: ['frontend:9113']  # nginx_exporter
